### ISSUE TITLE
Bug/Error with d._children.length...

### ISSUE THREAD

**Issue by radaced** [tmargolis/CollapsibleTree#1]
In all your nodeEnter.append("...")-functions you have a check like this: "return d.children || d._children.length". I found out when I used your CollapsibleTree visualization, that if when you click on the last node of a tree (this node is only a child node and not a parent node as well) a click event is fired. When you know click on the parent node above this child node it collapses in. If you now try to expand it back out again you get an error that the length property on d._children is not available when its null (or undefined) and the node can't be expanded anymore.
For me deleting all the checks on the length solved the problem but I don't know if there is more behind it (your code is quite advanced and I didn't have that much time to look further into it sorry...).

I hope you understand what I tried to say.

Greetings and many thanks for the good and functional implementation.
cheers, radaced

![collapsabletree](https://cloud.githubusercontent.com/assets/1215737/8567145/2ec2e42e-2563-11e5-82e3-ce1027d6c9ed.PNG)
![collapsabletree2](https://cloud.githubusercontent.com/assets/1215737/8567146/2ec4fcdc-2563-11e5-8042-647a9bb58b9a.PNG)

**Comment by tmargolis** [comment]
Thanks for alerting me to this issue. I was able to fix it by simply checking on click() if there were leaf nodes to find rather than assuming there were. This is a better solution than just removing the check at the title or text because that would also remove the special formatting for leaf nodes.

**Comment by radaced** [comment]
Ok yeah that's an idea too. You're very welcome. Anyway good implementation and thanks again.
